# When only b changes

In [108]:
from sklearn.datasets import make_regression

%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
import matplotlib.animation as animation
X,y = make_regression(n_samples=100, n_features=1, n_informative=1, n_targets=1,noise=27,random_state=12)

In [109]:
print(X.shape)
print(y.shape)

(100, 1)
(100,)


In [110]:
plt.plot(X,y)
plt.show()

In [111]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X,y)
print(reg.coef_)
print(reg.intercept_)

[39.49650254]
-2.0858976035131436


In [112]:
len(y)

100

In [113]:
b = -90
m = 39.49
lr = 0.001
all_b = []
all_cost = []

epochs = 25

for i in range(epochs):
    slope = 0
    cost = 0
    for j in range(X.shape[0]):
        slope = slope - 2*(y[j] - (m * X[j]) -  b)
        cost = cost + (y[j] - m * X[j] -b) ** 2

    b = b - (lr * slope)
    all_b.append(b)
    all_cost.append(cost)
    y_pred = m * X + b
    plt.plot(X,y_pred)
plt.scatter(X,y)

In [114]:
len(y)

100

In [115]:
all_b = np.array(all_b).ravel()
all_b

array([-72.41736719, -58.35126095, -47.09837595, -38.09606796,
       -30.89422156, -25.13274444, -20.52356275, -16.83621739,
       -13.88634111, -11.52644008,  -9.63851926,  -8.1281826 ,
        -6.91991327,  -5.95329781,  -5.18000544,  -4.56137155,
        -4.06646443,  -3.67053874,  -3.35379819,  -3.10040574,
        -2.89769179,  -2.73552062,  -2.60578369,  -2.50199415,
        -2.41896251])

In [116]:
all_cost = np.array(all_cost).ravel()
all_cost

array([845684.49791372, 567450.41915415, 389380.60874803, 275415.93008811,
       202478.53574576, 155798.60336666, 125923.44664403, 106803.34634155,
        94566.48214796,  86734.88906407,  81722.66949037,  78514.84896321,
        76461.84382583,  75147.9205379 ,  74307.00963363,  73768.82665489,
        73424.3895485 ,  73203.94980041,  73062.86836164,  72972.57624082,
        72914.78928349,  72877.80563081,  72854.13609309,  72838.98758895,
        72829.2925463 ])

In [117]:
fig, ax = plt.subplots(figsize=(9,5))
#fig.set_tight_layout(True)

x_i = np.arange(-3, 3, 0.1)
y_i = x_i*m -90
ax.scatter(X, y)
line, = ax.plot(x_i, x_i*50 - 4, 'r-', linewidth=2)

def update(i):
    label = 'epoch {0}'.format(i + 1)
    line.set_ydata(x_i*m + all_b[i])
    ax.set_xlabel(label)
    return line, ax

anim = FuncAnimation(fig, update, repeat=True, frames=epochs, interval=500)

f = r"animation.gif"
writergif = animation.PillowWriter(fps=2)
anim.save(f, writer=writergif)

<IPython.core.display.Javascript object>

In [118]:
len(y)

100

In [78]:
import matplotlib.pyplot as plt
import matplotlib.animation as animation

# DATA (example)
num_epochs = list(range(1, 26))
all_cost = [i * 80000 for i in range(25)]

fig, axis = plt.subplots(figsize=(9,5))
axis.set_xlim(0, 26)
axis.set_ylim(0, max(all_cost) * 1.1)
axis.set_xlabel("Epoch")
axis.set_ylabel("Loss")

line, = axis.plot([], [], lw=2)
epoch_text = axis.text(0.7, 0.9, "", transform=axis.transAxes)

xdata, ydata = [], []

def animate(i):
    xdata.append(num_epochs[i])
    ydata.append(all_cost[i])
    line.set_data(xdata, ydata)
    epoch_text.set_text(f"Epoch {i+1}")
    return line, epoch_text


anim = animation.FuncAnimation(
    fig,
    animate,
    frames=len(num_epochs),
    interval=500,
    repeat=False
)

anim.save("animation1.gif", writer=animation.PillowWriter(fps=2))


<IPython.core.display.Javascript object>

In [79]:
fig = plt.figure(figsize=(9,5))
axis = plt.axes(xlim =(0, 26), ylim =(-90, 0))

line, = axis.plot([], [], lw = 2)

xdata, ydata = [], []

# animation function
def animate(i):
    label = 'epoch {0}'.format(i + 1)
    xdata.append(num_epochs[i])
    ydata.append(all_b[i])
    line.set_data(xdata, ydata)
    axis.set_xlabel(label)

    return line,

# calling the animation function
anim = animation.FuncAnimation(fig, animate, frames = 25,repeat=False, interval = 500)

f = r"animation2.gif"
writergif = animation.PillowWriter(fps=2)
anim.save(f, writer=writergif)

<IPython.core.display.Javascript object>

In [81]:
import matplotlib.pyplot as plt
import matplotlib.animation
import numpy as np

fig, ax = plt.subplots()
ax.plot(all_b, all_cost)
x, y = [],[]
sc = ax.scatter(x,y,color='red',marker='+')
plt.xlim(-90,20)
plt.ylim(0,2000000)

def animate(i):
    label = 'epoch {0}'.format(i + 1)
    x.append(all_b[i])
    y.append(all_cost[i])
    sc.set_offsets(np.c_[x,y])
    ax.set_xlabel(label)

ani = matplotlib.animation.FuncAnimation(fig, animate,
                frames=25, interval=500, repeat=True)
plt.show()

f = r"animation3.gif"
writergif = animation.PillowWriter(fps=2)
ani.save(f, writer=writergif)

<IPython.core.display.Javascript object>

In [95]:
X

array([ 0.31866529, -1.52898548, -0.57188106, -0.9691765 , -1.16625876,
       -0.39787973, -0.10586232, -0.91386915,  0.23249044,  1.02921118,
        0.64076111, -0.14333741, -1.53472134, -0.57181673,  0.94357539,
        0.52733267,  1.00094276, -0.68142588, -0.12022767, -0.99720384,
       -0.10526799,  2.24181779,  1.63646291, -0.71626359,  1.34235637,
       -1.68175651, -1.44635944,  1.20979645, -1.25922352,  1.33583134,
       -1.2151688 ,  0.00512708,  0.05052283,  0.86761195,  1.09595612,
        0.5018723 ,  0.14655971, -1.00100155, -1.78809425,  0.07325207,
       -2.21853495, -1.00956165,  0.2424395 ,  0.22271946,  0.35622301,
       -0.051415  ,  0.13884618, -0.46139494, -0.4663511 ,  0.6778061 ,
       -0.71385629, -0.3843588 ,  0.1597877 , -0.33759525, -0.58526828,
        0.47245699, -0.68887869, -1.70073563,  0.75314283,  1.40772776,
       -1.02953021,  1.01251548,  0.27239104,  0.21497595,  0.25777259,
        0.53513589, -0.64743078,  0.80263045,  0.87196812, -0.60

In [121]:
y

array([  46.37886378,  -80.92579724,    0.42043064,  -57.59267439,
        -23.72227962,   -1.05573192,  -39.63556608,  -72.22798324,
         38.68337566,   17.87846594,   25.30517073,   16.98985038,
        -79.57828802,  -43.10357982,   15.8223764 ,   24.35055453,
         44.39248277,  -38.19457508,  -48.12243529,  -36.35364415,
         -0.50953308,   96.97288477,   43.42417788,  -46.51607749,
         67.90388358,   -9.96500882,  -65.15902135,    0.41923934,
        -58.44952862,   49.76635354,  -31.78989561,   -1.35372377,
         13.27306618,  120.48797505,   13.85385111,   56.64158875,
        -22.00098451,  -72.2865396 ,  -94.13872999,   25.4116377 ,
        -84.79189004,  -17.35167337,  -12.32349882,   20.50170077,
         30.92130499,  -35.44140566,   15.33641881,  -39.78438581,
        -20.85633891,   28.93964358,  -19.15604013,   -7.5045196 ,
         18.56190554,   15.61046642,  -88.05342596,   51.96392273,
          5.58565765,  -55.53796762,   12.88064274,   53.72125

In [120]:
len(y)

100

In [97]:
X.shape[0]

100

In [101]:
b_input = np.linspace(-90,90,100)

In [103]:
b_input

array([-90.        , -88.18181818, -86.36363636, -84.54545455,
       -82.72727273, -80.90909091, -79.09090909, -77.27272727,
       -75.45454545, -73.63636364, -71.81818182, -70.        ,
       -68.18181818, -66.36363636, -64.54545455, -62.72727273,
       -60.90909091, -59.09090909, -57.27272727, -55.45454545,
       -53.63636364, -51.81818182, -50.        , -48.18181818,
       -46.36363636, -44.54545455, -42.72727273, -40.90909091,
       -39.09090909, -37.27272727, -35.45454545, -33.63636364,
       -31.81818182, -30.        , -28.18181818, -26.36363636,
       -24.54545455, -22.72727273, -20.90909091, -19.09090909,
       -17.27272727, -15.45454545, -13.63636364, -11.81818182,
       -10.        ,  -8.18181818,  -6.36363636,  -4.54545455,
        -2.72727273,  -0.90909091,   0.90909091,   2.72727273,
         4.54545455,   6.36363636,   8.18181818,  10.        ,
        11.81818182,  13.63636364,  15.45454545,  17.27272727,
        19.09090909,  20.90909091,  22.72727273,  24.54

In [119]:
cost_input = []

for i in range(len(b_input)):
    this_cost = 0
    for j in range(X.shape[0]):
        this_cost = this_cost + (y[j] - m*X[j] - b_input[i])**2
    # cost_input.append(this_cost)
    print(this_cost)


[845684.49791372]
[814046.65314202]
[783069.96539511]
[752754.434673]
[723100.06097568]
[694106.84430316]
[665774.78465542]
[638103.88203249]
[611094.13643434]
[584745.54786099]
[559058.11631243]
[534031.84178866]
[509666.72428969]
[485962.76381551]
[462919.96036613]
[440538.31394153]
[418817.82454174]
[397758.49216673]
[377360.31681652]
[357623.2984911]
[338547.43719048]
[320132.73291464]
[302379.1856636]
[285286.79543736]
[268855.56223591]
[253085.48605925]
[237976.56690739]
[223528.80478031]
[209742.19967804]
[196616.75160055]
[184152.46054786]
[172349.32651996]
[161207.34951686]
[150726.52953855]
[140906.86658503]
[131748.36065631]
[123251.01175237]
[115414.81987324]
[108239.78501889]
[101725.90718934]
[95873.18638458]
[90681.62260462]
[86151.21584945]
[82281.96611907]
[79073.87341349]
[76526.9377327]
[74641.1590767]
[73416.5374455]
[72853.07283909]
[72950.76525747]
[73709.61470065]
[75129.62116862]
[77210.78466138]
[79953.10517894]
[83356.58272129]
[87421.21728843]
[92147.00888037

# when m and b both changes

In [140]:
from sklearn.datasets import make_regression

import numpy as np
import matplotlib.pyplot as plt
%matplotlib notebook
from matplotlib.animation import FuncAnimation
import matplotlib.animation as animation
X,y = make_regression(n_samples=100, n_features=1, n_informative=1, n_targets=1,noise=27,random_state=12)
plt.scatter(X,y)

In [141]:
b = -520
m = 600
lr = 0.001
all_b = []
all_m = []
all_cost = []

epochs = 30

for i in range(epochs):
    slope_b = 0
    slope_m = 0
    cost = 0
    for j in range(X.shape[0]):
        slope_b = slope_b - 2*(y[j] - (m * X[j]) -  b)
        slope_m = slope_m - 2*(y[j] - (m * X[j]) -  b)*X[j]
        cost = cost + (y[j] - m * X[j] -b) ** 2

    b = b - (lr * slope_b)
    m = m - (lr * slope_m)
    all_b.append(b)
    all_m.append(m)
    all_cost.append(cost)

In [142]:
print(all_b)
print(all_m)

[array([-400.24020809]), array([-308.47072737]), array([-238.09331625]), array([-184.07570443]), array([-142.57798035]), array([-110.66847699]), array([-86.10765045]), array([-67.1836256]), array([-52.58701297]), array([-41.31558294]), array([-32.60164663]), array([-25.85671092]), array([-20.62927889]), array([-16.57265767]), array([-13.42038747]), array([-10.96747703]), array([-9.05606487]), array([-7.56445544]), array([-6.39873021]), array([-5.48632436]), array([-4.77110475]), array([-4.20959537]), array([-3.76808016]), array([-3.42037743]), array([-3.14612848]), array([-2.9294804]), array([-2.75807116]), array([-2.62224685]), array([-2.51445715]), array([-2.42878806])]
[array([460.07820565]), array([354.81085947]), array([275.66330632]), array([216.19427623]), array([171.54393142]), array([138.04684518]), array([112.93947383]), array([94.13909048]), array([80.07675578]), array([69.57114364]), array([61.73325107]), array([55.89445042]), array([51.55218103]), array([48.32896775]), arr

In [144]:
fig, ax = plt.subplots(figsize=(9,5))
fig.set_tight_layout(True)

x_i = np.arange(-3, 3, 0.1)
y_i = x_i*(-39) -150
ax.scatter(X, y)
line, = ax.plot(x_i, x_i*50 - 4, 'r-', linewidth=2)

def update(i):
    label = 'epoch {0}'.format(i + 1)
    line.set_ydata(x_i*all_m[i] + all_b[i])
    ax.set_xlabel(label)
    return line, ax

anim = FuncAnimation(fig, update, repeat=True, frames=epochs, interval=500)

f = r"animation4.gif"
writergif = animation.PillowWriter(fps=2)
anim.save(f, writer=writergif)

<IPython.core.display.Javascript object>

In [156]:
# Cost function
# creating a blank window
# for the animation
num_epochs = list(range(0,25))
fig = plt.figure(figsize=(9,5))
axis = plt.axes(xlim =(0, 26), ylim =(0, 4500000))

line, = axis.plot([], [], lw = 2)

xdata, ydata = [], []

# animation function
def animate(i):
    label = 'epoch {0}'.format(i + 1)
    xdata.append(num_epochs[i])
    ydata.append(all_cost[i])
    line.set_data(xdata, ydata)
    axis.set_xlabel(label)

    return line,

# calling the animation function
anim = animation.FuncAnimation(fig, animate, frames = 25,repeat=False, interval = 500)

f = r"animation5.gif"
writergif = animation.PillowWriter(fps=2)
anim.save(f, writer=writergif)

<IPython.core.display.Javascript object>

In [154]:
# intercept graph
num_epochs = list(range(0,25))
fig = plt.figure(figsize=(9,5))
axis = plt.axes(xlim =(0, 26), ylim =(-400, 10))

line, = axis.plot([], [], lw = 2)

xdata, ydata = [], []

# animation function
def animate(i):
    label = 'epoch {0}'.format(i + 1)
    xdata.append(num_epochs[i])
    ydata.append(all_b[i])
    line.set_data(xdata, ydata)
    axis.set_xlabel(label)

    return line,

# calling the animation function
anim = animation.FuncAnimation(fig, animate, frames = 25,repeat=False, interval = 500)

f = r"animation6.gif"
writergif = animation.PillowWriter(fps=2)
anim.save(f, writer=writergif)

<IPython.core.display.Javascript object>

In [153]:
# intercept graph
num_epochs = list(range(0,30))
fig = plt.figure(figsize=(9,5))
axis = plt.axes(xlim =(0, 31), ylim =(20, 460))

line, = axis.plot([], [], lw = 2)

xdata, ydata = [], []

# animation function
def animate(i):
    label = 'epoch {0}'.format(i + 1)
    xdata.append(num_epochs[i])
    ydata.append(all_m[i])
    line.set_data(xdata, ydata)
    axis.set_xlabel(label)

    return line,

# calling the animation function
anim = animation.FuncAnimation(fig, animate, frames = 30,repeat=False, interval = 500)

f = r"animation7.gif"
writergif = animation.PillowWriter(fps=2)
anim.save(f, writer=writergif)

<IPython.core.display.Javascript object>